# Generated by Django 5.1.5 on 2025-01-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products_in_inventory',
            new_name='Products_in_inventorys',
        ),
    ]
