# Generated by Django 5.1.5 on 2025-01-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_manager', '0002_rename_products_in_inventory_products_in_inventorys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products_in_inventorys',
            new_name='Products_in_inventories',
        ),
    ]
